spring:
  datasource:
    url: jdbc:h2:file:./data/learnpath-demo;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      repositories:
        enabled: false

management:
  health:
    redis:
      enabled: true
