<template>
  <div class="dashboard-grid">
    <section class="focus-card glass-card"><div class="focus-content"><span class="eyebrow"><i></i> 今日学习焦点</span><h2>数据结构 · 第 4 章</h2><p>二叉树与遍历算法</p><div class="focus-meta"><span>◷ 预计 35 分钟</span><span>知识点 6 个</span></div><RouterLink class="primary-link" to="/courses/1">继续学习 <span>→</span></RouterLink></div><div class="focus-ring"><div><strong>68%</strong><span>课程进度</span></div></div></section>
    <section class="streak-card glass-card"><div class="card-heading"><div><span class="mini-icon purple">↗</span><h2>连续学习</h2></div><button>本周⌄</button></div><div class="streak-number"><strong>12</strong><span>天</span><em>创下新纪录！</em></div><div class="week-row"><div v-for="(day, index) in ['一','二','三','四','五','六','日']" :key="day" :class="{ today: index === 4, future: index > 4 }"><i>{{ index < 5 ? '✓' : '' }}</i><span>{{ day }}</span></div></div></section>
    <section class="tasks-card glass-card"><div class="card-heading"><div><span class="mini-icon blue">✓</span><h2>今日任务</h2></div><span class="counter">3 / 5</span></div><div class="task-list"><label class="task done"><input checked type="checkbox" /><i></i><span><strong>完成算法章节练习</strong><small>数据结构 · 20 分钟</small></span><em>+15 XP</em></label><label class="task done"><input checked type="checkbox" /><i></i><span><strong>复习英语核心词汇</strong><small>大学英语 · 15 分钟</small></span><em>+10 XP</em></label><label class="task"><input type="checkbox" /><i></i><span><strong>观看数据库课程视频</strong><small>数据库原理 · 35 分钟</small></span><em>+20 XP</em></label><label class="task"><input type="checkbox" /><i></i><span><strong>订正昨日错题</strong><small>错题本 · 10 分钟</small></span><em>+10 XP</em></label></div></section>
    <section class="chart-card glass-card"><div class="card-heading"><div><span class="mini-icon cyan">◒</span><h2>本周学习趋势</h2></div><span class="trend-up">↑ 18%</span></div><div class="chart-summary"><strong>8.6</strong><span>小时</span><small>比上周多 1.3 小时</small></div><div class="bar-chart"><div v-for="(height, index) in [48, 63, 42, 76, 88, 31, 18]" :key="index"><i :style="{ height: `${height}%` }" :class="{ highlight: index === 4 }"></i><span>{{ ['一','二','三','四','五','六','日'][index] }}</span></div></div></section>
    <section class="recommend-card glass-card"><div class="recommend-icon">✦</div><div><span>智能推荐</span><h2>排序算法专项突破</h2><p>根据最近的练习表现，你在“快速排序”知识点上还可以继续提升。</p></div><RouterLink class="recommend-link" to="/courses/1">查看推荐 →</RouterLink></section>
  </div>
</template>
